ALTER TABLE invoices ADD COLUMN IF NOT EXISTS extra_children INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS parents_above_80 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS extra_children_premium NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS parents_above_80_premium NUMERIC(10,2) NOT NULL DEFAULT 0;
